### ISSUE TITLE
Alex's next post on 05/01

### ISSUE THREAD

**Issue by beatrizcp87** [Helabs/blog#335]
Hey Alex, guess what! Your post will be the first of the year.
Please contact me if you have any problens, we have another post on the line. ;)

**Comment by beatrizcp87** [comment]
![navi](https://cloud.githubusercontent.com/assets/5721795/5781599/4c1bfd58-9d9b-11e4-8fdb-b2819464ec84.png)

HEY LISTEN!
I still want your post :'(

**Comment by alexbrahastoll** [comment]
Hi Bia,

I have some ideas and I will start writing my next post soon. However, since I don't have investment days anymore (I'm working at Atende Simples), it will probably take a bit longer. I think it will be ready at my next turn.

Cheers =)
