### ISSUE TITLE
Fiuza's next post 25/03

### ISSUE THREAD

**Issue by beatrizcp87** [Helabs/blog#366]
All that is gold does not glitter, 
not all those who wander are lost; 
the old that is strong does not wither, 
deep roots are not reached by the frost.

After this moment of poetry, I think you have enough inspiration  to write your new post. Have fun ;)

**Comment by guiloyins** [comment]
Anyone can love a thing because. 
That's as easy as putting a penny in your pocket. 
But to love something despite. To know the flaws and love them too. 
That is rare and pure and perfect.

So, love me, even when I don`t write my post in time. I will!

**Comment by beatrizcp87** [comment]
Own <3
