### ISSUE TITLE
Tomas new post 27/03

### ISSUE THREAD

**Issue by beatrizcp87** [Helabs/blog#367]
"Where words fail, music speaks". But this is no escuse, you still have a post to do.
Have fun ;)

**Comment by tomasmuller** [comment]
@beatrizcp87 hahah :monkey_face: :smile: 

Nice quote! :+1: 

I'll write a nice one. Wait to see! :neckbeard: :musical_note:

**Comment by beatrizcp87** [comment]
Uhuuuul /,,/

**Comment by beatrizcp87** [comment]
</3
